export const SET_ADMIN_FILTER = 'SET_ADMIN_FILTER';


// Searching Registrants
export const SEARCH_REGISTRANTS_SUCCESS = 'SEARCH_REGISTRANTS_SUCCESS';
export const SEARCH_REGISTRANTS_ERROR = 'SEARCH_REGISTRANTS_ERROR';
